version: "3.7"

services:
  db:
    restart: always
    image: postgres:12-alpine
    container_name: db
    env_file:
      - ./config/.env.dev_db
    ports:
      - '5432:5432'
  web:
    build: .
    image: web
    container_name: app
    command: python main.py run -h 0.0.0.0
    env_file:
      - ./config/.env.dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
  worker:
    image: web
    command: python main.py run_worker
    container_name: worker1
    env_file:
      - ./config/.env.dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.0.5-alpine
    container_name: redis
    ports:
    - 6379:6379