version: "3.7"

services:
  db:
    restart: always
    image: postgres:12-alpine
    container_name: db
    env_file:
      - ./config/.env.dev_db
    ports:
      - '5432:5432'
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  web:
    build: app
    container_name: app
    command: python manage.py run -h 0.0.0.0
    env_file:
      - ./config/.env.dev
    volumes:
    - ./app/:/app/
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - 9000:9000
    depends_on:
      - redis
  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin
    restart: always
    env_file:
      - ./config/.env.DEV_pgadmin
    volumes:
    - ./pgadmin_data:/var/lib/pgadmin
    ports:
    - "80:80"
    links:
      - "db:pgsql-server"
  redis:
    image: redis:6-alpine
    container_name: redis