version: "3.7"

services:
  db:
    restart: always
    build:
      context: .
      dockerfile: postgresDocker
    container_name: db
    env_file:
      - ../configuration/.env.dev.db
    ports:
    - 5432:5432
  web:
    build: ./services/web
    command: flask run --host 0.0.0.0
    container_name: "web"
    env_file:
      - ../configuration/.env.dev
    volumes:
    - ./services/web/:/usr/src/api/
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - 5000:5000
    links:
      - db:db
  rest:
    build: ./services/restapi
    container_name: "rest"
    env_file:
      - ../configuration/.env.DEV_REST
    volumes:
      - ./services/restapi/:/usr/src/restapi/
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - 8080:8080
    links:
      - db:db